GET http://localhost:3333/users

###

POST http://localhost:3333/users/signup
content-type: application/json

{
    "name": "Pedro Andrade Giroldo",
    "email": "pedrogiroldo40@gmail.com",
    "password": "teste1"
}

###

POST http://localhost:3333/users/login
content-type: application/json

{
    "email": "pedrogiroldo40@gmail.com",
    "password": "teste1"
}

###

POST http://localhost:3333/users/refresh/3aa06cf0-01f3-46e7-960f-980f8575f6d2