GET http://localhost:3333/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZjY1ZDY3NC0yYjBjLTQxYTMtYWVmZC01MzM4YzVhNDQ5NmUiLCJpYXQiOjE3MjA3MTgzMjUsImV4cCI6MTcyMTkyNzkyNX0.rORktcPB2n8vyPSL3sdahGboAOAXK3sxnisAqDhwZQM

###

POST http://localhost:3333/users/signup
content-type: application/json

{
    "name": "Pedro Andrade Giroldo",
    "email": "pedrogiroldo41@gmail.com",
    "password": "teste1"
}

###

POST http://localhost:3333/users/login
content-type: application/json

{
    "email": "pedrogiroldo40@gmail.com",
    "password": "teste1"
}

###

POST http://localhost:3333/users/refresh/3aa06cf0-01f3-46e7-960f-980f8575f6d2