GET http://localhost:3333/users

###

POST http://localhost:3333/users/signup
content-type: application/json

{
    "name": "Pedro Andrade Giroldo",
    "email": "pedrogiroldo40@gmail.com",
    "password": "teste1"
}

###

POST http://localhost:3333/users/login
content-type: application/json

{
    "email": "pedrogiroldo40@gmail.com",
    "password": "teste1"
}

###

POST http://localhost:3333/users/refresh/c6949e4d-b097-43bb-817b-b8cfcb128832